extend schema @link(url: "https://specs.apollo.dev/link/v1.0")

extend schema
  @link(
    url: "https://specs.apollo.dev/federation/v2.6"
    import: ["@key", "@external", "@shareable"]
  )

type Image @key(fields: "id") {
  id: Int!
  url: String
}

extend type Product @key(fields: "upc") {
  id: Int! @shareable
  upc: String!
  images: [Image]
}
