extend schema
  @link(
    url: "https://specs.apollo.dev/federation/v2.3"
    import: ["@key", "@shareable"]
  )

type Review {
  body: String
  product: Product
}

type Product @key(fields: "upc") {
  id: Int! @shareable
  upc: String!
  reviews: [Review]
}
